### ISSUE TITLE
bad token

### ISSUE THREAD

**Issue by kamranr123** [gi097/WhatsApi-Android#1]
hi
i update whatsapp version code but i recieve bad token error
please help me, i cant connect to whatsapp server

my WHATSAPP_USER_AGENT is :

private final String WHATSAPP_USER_AGENT = "WhatsApp/2.12.334 S40Version/14.26 Device/Nokia302"

**Comment by gi097** [comment]
First of all your useragent is incorrect. 2.12.334 is an Android client, not S40. Second problem is that you need to update the releaseTime too. 

Please use my original useragent.

Regards.

**Comment by kamranr123** [comment]
i used your original code:
```
private final String WHATSAPP_DEVICE = "S40"; // The device name.
private final String WHATSAPP_VER = "2.12.96"; // The WhatsApp version.
private final String WHATSAPP_USER_AGENT = "WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302";// User agent used in request/registration code.
```

and update release time to :

```
private static final String RELEASE_TIME = "1446370412325";
```

but i got bad token again

```
{"reason":"bad_token","status":"fail"}
```

**Comment by gi097** [comment]
I will update it today. Please wait, you will see the commit soon.

**Comment by kamranr123** [comment]
thank for replay

**Comment by gi097** [comment]
See commit: 383532b2efdff0367b1add367f4174c41b76be16

**Comment by kamranr123** [comment]
thanks
its work now
