### ISSUE TITLE
Hi, about WhatsAPI

### ISSUE THREAD

**Issue by NirHUJI** [gi097/WhatsApi-Android#2]
Can you explain to me what exactly are the changes that you are doing for converting whatsApi to be android compatible??
I have already succeeded in making wathsAPI android compatible and there aren't many changes at all...

**Comment by gi097** [comment]
True that, I ported the library, but I also make a client with GUI for android. It's going to be a total new WhatsApp. However maybe you can help me with processing receive messages?

**Comment by NirHUJI** [comment]
Right now i don't have any spare time (final exams) but in about a month i hope i'll be free and could help you...
A liitle suggestion- Maybe I am mistaken but it seems right now that you mixed the client files with the ported API. I suggest that you separate the ported API from the client you are building, so people could easly use the API with their own client.

**Comment by gi097** [comment]
They can fork previous commits, however it is better to implement all the stuff in my opinion. Good luck with your exams!
