### ISSUE TITLE
error on UntrustedIdentityException == >> at org.whispersystems.libaxolotl.SessionBuilder.process(SessionBuilder.java:262)

### ISSUE THREAD

**Issue by ilhamiarie** [gi097/WhatsApi-Android#4]
Hello @gi097 thanks for your code,
i always get this exception, is there any solution for this..

thanks.

**Comment by ilhamiarie** [comment]
i got reply from whatsapp.
<iq from="s.whatsapp.net" type="result" id="cipherKeys-1449920997-2">
<list>
<user jid="6281336668199@s.whatsapp.net">
<registration>1838e674</registration><type>05</type><identity>77836d885375292af989ccdb038105a09c3f6b67614774d44e2acc26e4dc8d53</identity><skey>
<id>000000</id><value>5b306450cb98b5569f22ff246d63c59a260b804ff1a8a0c500a9238f8c063e48</value><signature>560e7856bc7e4d5a39c23da46a8b188fb7b4ff1a92121b5994a1ecb569f5246e8bfc0e0d3e3778a90555fcac68845359adb0133de8426f6b28bda7586b744385</signature>
</skey><key>
<id>5fd6c1</id><value>81b5d94b3b0e6db332f42cf5d7e86199e26304bdac19853418ba15f902146922</value>
</key>
</user>
</list>
</iq>

**Comment by gi097** [comment]
It needs some more work regarding the adjustId() and the deAdjustId() functions. I pushed a new commit, which you can try. However, I don't know the exact problem, but it will be fixed.

**Comment by gi097** [comment]
Seems to be fixed now. Enjoy.

**Comment by ilhamiarie** [comment]
hi @gi097 thanks for all, 
where I can see the code that has been updated? i see no update code on master.. thanks.
